PURITAN_VALUES = ['amateur', 'amateurarchives', 'amateurteen', 'amateurvideos', 'britishporn', 'camwhores', 'collegeamateurs',
            'gonewildcurvy', 'homemadexxx', 'instagramporn', 'nswf_amateurass', 'nudeamateurporn', 'pornamateurs',
            'wouldyoufuckmywife', 'anal', 'analfisting', 'analfucking', 'analgaping', 'analgw', 'analporn', 'analtoys',
            'analvids', 'assfucking', 'assgaping', 'asshole', 'asslick', 'buttplug', 'facedownassup', 'fisting',
            'gapedass', 'gapingassholes', 'ass', 'assholebehindthong', 'assinthong', 'asstastic', 'cycleseats',
            'datgap', 'facedownassup', 'nsfw_anal_pics', 'theunderbun', 'bhmgonewild', 'bulges', 'cuteguybutts',
            'jockstraps', 'jockwatch', 'ladybonersgw', 'malemodels', 'malespandex', 'maleunderwear', 'mangonewild',
            'aparthigh', 'bbw', 'bonermaterial', 'bigtitssmalltits', 'bimbofetish', 'asianhotties', 'asiangirls',
            'babes4porn', 'bottomless_vixens', 'bustypetite', 'candidfashionpolice', 'celebnsfw', 'blondes', 'brunette',
            'brunettes', 'christiangirls', 'classicscreenbeauties', 'curls', 'curvy', 'darkangels', 'diorabaird',
            'dsls', 'garterbelts', 'ginger', 'girlswithglasses', 'gonewild', 'gonewildcolor', 'gonewildplus', 'gravure',
            'groupofnudegirls', 'hairbra', 'hegre', 'horny_porn_pics', 'hot_pics', 'hub_porn', 'indianbabe',
            'iwanttofuckher', 'jenniejune', 'jordancarver', 'just18', 'legalteens', 'legsup', 'lingerie', 'metart',
            'milf', 'notsafefornature', 'nsfw', 'nsfwblogs', 'nsfwoutfits', 'nude', 'onoff', 'palegirls', 'petiteporn',
            'photoshopbattlesnsfw', 'playboy', 'porn_beauty', 'porn_imgur', 'ravenhaired', 'realgirls', 'redhead',
            'redheads', 'seethru', 'sexyfrex', 'sexygirlsinboots', 'sexygirlsinjeans', 'shewantstofuck', 'slingbikini',
            'stockings', 'suicidegirls', 'thick', 'thinspo', 'tightdresses', 'twingirls', 'unashamed', 'upskirt',
            'voluptuous', 'womenofcolor', 'womenofcolour', 'workgonewild', 'wtsstadamit', 'xsmallgirls', 'blowbang',
            'blowjobs', 'blowjobsandwich', 'cfnmfetish', 'cumshotvideos', 'cumsluts', 'cumswallowing', 'facefuck',
            'girlsfinishingthejob', 'randomactsofblowjob', 'amateurbondage', 'bdsm', 'bondage', 'collared',
            'damselsindistress', 'forcedorgasms', 'humiliation', 'strugglefucking', 'boobs', 'naturaltitties',
            'boobtube', 'braww', 'boobbounce', 'boltedontits', 'boobies', 'pokies', 'tittydrop', 'theunderboob',
            'sweatermeat', 'hugeboobs', 'tinytits', 'titlist', 'ageplaying', 'cat_girls', 'cosporn', 'nsfwcosplay',
            'petplay', 'tipofmypenis', 'cumfetish', 'cummingonfigurines', 'jizzycarts', 'tributeme', 'dicks',
            'foreskin', 'hugedicks', 'massivecock', 'penis', 'tinydick', 'askwomen', 'autogynephilia',
            'avocadosgonewild', 'bdsmcommunity', 'bdsmpersonals', 'bigdickproblems', 'bisexual', 'crossdressing',
            'cuckoldcommunity', 'deadbedrooms', 'dildology', 'freekarmansfw', 'imgoingtohellforthis',
            'nsfw_redditslist', 'nsfw_subreddits', 'nsfw411', 'nsfwnews', 'nsfwtodayilearned', 'polyamory', 'pornid',
            'sex', 'sextoys', 'softcorenights', 'swingcommunity', 'twoxsex', 'wifesharing', 'animalromance',
            'buttsharpies', 'distension', 'facesitting', 'feet', 'feet_nsfw', 'ffsocks', 'fuckingmachines',
            'gonewildaudio', 'gonewildhairy', 'grool', 'hairyarmpits', 'insertions', 'japanporn', 'jilling',
            'men_in_panties', 'needmoreporn', 'objects', 'oldenporn', 'openholes', 'preggoporn', 'pregporn',
            'shinyporn', 'tentai', 'tickling', 'weddingringsshowing', 'nsfw_wtf', 'nsfwadviceanimals', 'nsfwfunny',
            'redbandtrailers', 'bisexy', 'broslikeus', 'chesthairporn', 'dickgirls', 'gaybears', 'gaybrosgonewild',
            'gaycumsluts', 'gaygifs', 'gaykink', 'gaymersgonewild', 'gaynsfw', 'gayporn', 'gaysex', 'gaysexxxvideos',
            'gaywatersports', 'gonewildtrans', 'lgbtgonewild', 'lovegaymale', 'manass', 'mansex', 'menslegs',
            'nsfw_gay', 'nsfw_gay_porn', 'pegging', 'publicboys', 'sissies', 'tgifs', 'tgirls', 'traps', 'gilf',
            'nsfw_gif', 'nsfw_gifs', 'nsfw_gifsound', 'porn_gifs', 'xxx_animated_gifs', 'amailiu', 'angelinacrow',
            'cuckold', 'dirtysmall', 'doublep', 'doublepenetration', 'doublevaginal', 'dp_porn', 'dpgirls', 'dpsex',
            'gonewildcolor', 'groupsex', 'highresnsfw', 'jamesdeen', 'jennahaze', 'joymii', 'kristinarose', 'mandingo',
            'nsfwhardcore', 'o_faces', 'onherknees', 'porn', 'sexywallpapers', 'shelikesitrough', 'spitroast',
            'spitroasted', 'twistys', 'victoriaraeblack', 'xart', 'avatarporn', 'ecchi', 'furry', 'futanariÿ', 'hentai',
            'pantsu', 'portalporn', 'rule34', 'rule34_comics', 'vore', 'yiff', 'yiffcomics', 'jerk', 'off', 'joi',
            'jerkinginstruction', 'jerkingencouragement', 'lesbian', 'chickflixxx', 'dyke', 'dykesgonewild', 'lesbians',
            'lesdom', 'scissoring', 'abuseporn', 'animalromance', 'cumonclothes', 'earthpornporn', 'gonewild', 'gore',
            'guro', 'hypnogonewild', 'incestvideos', 'ohcumon', 'painal', 'squidsgonewild', 'whalesgonewild',
            'zombiesgonewild', 'dirtygaming', 'gamersgonewild', 'girlsdoingnerdythings', 'pee', 'peegonewild', 'piss',
            'poop', 'beef_flaps', 'bigclit', 'butterflywings', 'celebritypussy', 'creampie', 'creampies', 'hairypussy',
            'lipsthatgrip', 'pussy', 'pussygape', 'rearpussy', 'simps', 'dirtypenpals', 'erotica', 'eroticliterature',
            'gonewildstories', 'hotwife', 'nsfwiama', 'sexystories']